apiVersion: v1
kind: Secret
metadata:
  name: sentinel-credentials
  namespace: sentinel-system
type: Opaque
stringData:
  admin: $2b$12$Wf8rnaWkoBwKN6jStSSYie1j3AmITOT6cU0M/CkebvzalUzXJ.Pi6
  jwt-secret: my-super-secret-jwt-key-2026
